addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1804
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-centos-8
  - INSTANCE=default-debian-9
  - INSTANCE=default-debian-10
  - INSTANCE=default-fedora-latest
  - INSTANCE=default-opensuse-leap-15
  - INSTANCE=input-file-resource-ubuntu-1604
  - INSTANCE=input-file-resource-ubuntu-1804
  - INSTANCE=input-file-resource-centos-6
  - INSTANCE=input-file-resource-centos-7
  - INSTANCE=input-file-resource-centos-8
  - INSTANCE=input-file-resource-debian-9
  - INSTANCE=input-file-resource-debian-10
  - INSTANCE=input-file-resource-fedora-latest
  - INSTANCE=input-file-resource-opensuse-leap-15
  - INSTANCE=client-ubuntu-1604
  - INSTANCE=client-ubuntu-1804
  - INSTANCE=client-centos-6
  - INSTANCE=client-centos-7
  - INSTANCE=client-centos-8
  - INSTANCE=client-debian-9
  - INSTANCE=client-debian-10
  - INSTANCE=client-fedora-latest
  - INSTANCE=client-opensuse-leap-15
  - INSTANCE=server-ubuntu-1604
  - INSTANCE=server-ubuntu-1804
  - INSTANCE=server-centos-6
  - INSTANCE=server-centos-7
  - INSTANCE=server-centos-8  
  - INSTANCE=server-debian-9
  - INSTANCE=server-debian-10
  - INSTANCE=server-fedora-latest
  - INSTANCE=server-opensuse-leap-15

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_FIPS=''
